# Generated by Django 2.1.5 on 2020-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0002_auto_20200426_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='pessangers', to='HelloWorld.Flight')),
            ],
        ),
    ]
